---
- name: Install Nginx WebServer
  hosts: all
  # hosts: centos
  become: yes

  pre_tasks:
  - debug:
      msg: 'Beginning Nginx Web server configuration. {{ ansible_distribution }}-{{ ansible_distribution_major_version}}'

  roles:
    - install

  post_tasks:
    - debug:
        msg: 'Nginx Web server has been configured.'